sequenceDiagram
    participant Cliente as Usuário
    participant Servidor as Servidor
    participant Sala as Usuários da Sala
    participant Quadro as Usuários do Quadro

    critical Autenticação do Usuário
        Cliente->>Servidor: connect <br/> (Estabelecer conexão WebSocket)
        Servidor-->>Cliente: connected <br/> (Conexão estabelecida)
    option Falha na autenticação
        Servidor-->>Cliente: error <br/> (Não autorizado)
    end
    Cliente-->>Servidor: room:join <br/> (Entrar na sala)

    Servidor-->>Sala: room:joined <br/> (Usuário online na sala)
    Servidor-->>Cliente: room:members <br/> (Lista de membros online na sala)
    
    Cliente-->>Servidor: board:join <br/> (Entrar no quadro)
    Servidor-->>Quadro: board:joined <br/> (Usuário entrou no quadro)
    Servidor-->>Cliente: board:viewers <br/> (Lista de visualizadores do quadro)
    
    Cliente-->>Servidor: board:write <br/> (Modificar o código)
    Servidor-->>Sala: board:typed <br/> (Indica que o usuário está escrevendo)
    Servidor-->>Quadro: board:written <br/> (Conteúdo do código)
    
    Cliente-->>Servidor: board:highlight <br/> (Destacar código)
    Servidor-->>Quadro: board:highlighted <br/> (Posição do destaque)
    
    Cliente-->>Servidor: disconnecting <br/> (Usuário desconectando)
    Servidor-->>Quadro: board:left <br/> (Usuário saiu do quadro)
    Servidor-->>Sala: room:left <br/> (Usuário saiu da sala)
    
